[package]
name = "doubledibs"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.2.0" }

[addresses]
doubledibs = "0x0"
test_admin = "0x69"
deployer = "0x292855f960c2cac03b141b1dfdcd0c48d6c65769e12e0b556a78077d7a9add68"
